create table if not exists public.alerts (
    alert_id bigint generated by default as identity primary key,
    alert_type text not null,
    severity text not null default 'info',
    title text not null default '',
    message text not null default '',
    timestamp_ms bigint not null,
    track_id text not null default '0',
    action text not null default 'unknown',
    confidence double precision not null default 0,
    source text not null default 'backend',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists alerts_timestamp_ms_idx on public.alerts (timestamp_ms desc);
create index if not exists alerts_type_idx on public.alerts (alert_type);

create table if not exists public.reports (
    report_id bigint generated by default as identity primary key,
    title text not null default 'Activity Summary',
    window_ms bigint not null,
    generated_at_ms bigint not null,
    insight jsonb not null,
    alert_counts jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists reports_generated_at_ms_idx on public.reports (generated_at_ms desc);

alter table public.alerts enable row level security;
alter table public.reports enable row level security;

drop policy if exists "Allow public read alerts" on public.alerts;
create policy "Allow public read alerts"
    on public.alerts
    for select
    to anon, authenticated
    using (true);

drop policy if exists "Allow public read reports" on public.reports;
create policy "Allow public read reports"
    on public.reports
    for select
    to anon, authenticated
    using (true);
